"""empty message

Revision ID: 66a138673d5e
Revises: ffdc0a98111c
Create Date: 2022-03-03 13:56:56.994593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a138673d5e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('is_yarn', sa.Boolean(), nullable=False),
    sa.Column('is_fiber', sa.Boolean(), nullable=False),
    sa.Column('is_notions', sa.Boolean(), nullable=False),
    sa.Column('is_pattern', sa.Boolean(), nullable=False),
    sa.Column('is_knitting', sa.Boolean(), nullable=False),
    sa.Column('is_crochet', sa.Boolean(), nullable=False),
    sa.Column('is_embroidery', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('makers')
    # ### end Alembic commands ###
