"""empty message

Revision ID: eb539719a96a
Revises: a2c3787d03f3
Create Date: 2022-03-09 13:37:41.712090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb539719a96a'
down_revision = 'a2c3787d03f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=4), nullable=False),
    sa.Column('is_yarn', sa.Boolean(), nullable=False),
    sa.Column('is_fiber', sa.Boolean(), nullable=False),
    sa.Column('is_notions', sa.Boolean(), nullable=False),
    sa.Column('is_pattern', sa.Boolean(), nullable=False),
    sa.Column('is_knitting', sa.Boolean(), nullable=False),
    sa.Column('is_crochet', sa.Boolean(), nullable=False),
    sa.Column('is_embroidery', sa.Boolean(), nullable=False),
    sa.Column('discount_code', sa.String(length=100), nullable=False),
    sa.Column('discount_details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
