"""empty message

Revision ID: d770489ee4d9
Revises: 996d4ead0ac5
Create Date: 2022-03-17 10:33:12.345142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd770489ee4d9'
down_revision = '996d4ead0ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('banner_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'banner_image')
    # ### end Alembic commands ###
