"""empty message

Revision ID: a2c3787d03f3
Revises: 66a138673d5e
Create Date: 2022-03-04 17:58:22.107859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c3787d03f3'
down_revision = '66a138673d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makers', sa.Column('country', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('makers', 'country')
    # ### end Alembic commands ###
